[package]
name = "cramino"
version = "0.14.5"
edition = "2021"
authors = ["Wouter De Coster decosterwouter@gmail.com"]
license = "MIT"
description = "A tool to quickly extract quality metrics from bam or cram files"
readme = "README.md"
homepage = "https://github.com/wdecoster/cramino"
repository = "https://github.com/wdecoster/cramino"
keywords = ["ont", "pacbio", "cram", "bam", "alignment"]
categories = ["command-line-utilities", "science"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
rust-htslib = "0.46.0"
log = "0.4.0"
env_logger = "0.11.1"
chrono = "0.4.22"
rayon = "1.5.3"
arrow = "50.0.0"
unzip-n = "0.1.2"
itertools = "0.12.1"

libz-sys = "1.1.12"
url = "2.5.0"
hts-sys = "2.1.1"

[dev-dependencies]
ctor = "0.2.4"
