[package]
name = "cramino"
version = "0.12.0"
edition = "2021"
authors = ["Wouter De Coster decosterwouter@gmail.com"]
license = "MIT"
description = "A tool to quickly extract quality metrics from bam or cram files"
readme = "README.md"
homepage = "https://github.com/wdecoster/cramino"
repository = "https://github.com/wdecoster/cramino"
keywords = ["ont", "pacbio", "cram", "bam", "alignment"]
categories = ["command-line-utilities", "science"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.6", features = ["derive"] }
rust-htslib = "0.44.1"
log = "0.4.0"
env_logger = "0.10.0"
checksums = "0.9.1"
chrono = "0.4.22"
rayon = "1.5.3"
arrow = "46.0.0"
unzip-n = "0.1.2"
itertools = "0.11.0"

libz-sys = "1.1.12"

[dev-dependencies]
ctor = "0.2.4"

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-mmacosx-version-min=10.12"]
