[package]
name = "cramino"
version = "0.9.7"
edition = "2021"
authors = ["Wouter De Coster decosterwouter@gmail.com"]
license = "MIT"
description = "A tool to quickly extract quality metrics from bam or cram files"
readme = "README.md"
homepage = "https://github.com/wdecoster/cramino"
repository = "https://github.com/wdecoster/cramino"
keywords = ["ont", "pacbio", "cram", "bam", "alignment"]
categories = ["command-line-utilities", "science"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.6", features = ["derive"] }
rust-htslib = "0.39.5"
log = "0.4.0"
env_logger = "0.8.4"
checksums = "0.9.1"
chrono = "0.4.22"
rayon = "1.5.3"
histo_fp = "0.2.1"
arrow = "26.0.0"
unzip-n = "0.1.2"
itertools = "0.10.5"

[dev-dependencies]
ctor = "0.1.26"

[target.x86_64-apple-darwin]
rustflags=["-C", "link-arg=-mmacosx-version-min=10.12"]